site_name: DCS AH-1G Cobra Manual

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.blocks.caption
  - toc:
      permalink: "#"

extra_css:
  - css/drafts.css
  - css/images.css
  - css/links.css
  - css/headers.css

nav:
  - AH-1G Manual: index.md
  - Support / Bug Reporting: support.md
  - Setup:
    - Installation: Setup/Installation.md
    - Keybinds: Setup/Keybinds.md
    - Special Options: Setup/SpecialOptions.md
    - Multicrew: Setup/Multicrew.md
  - Cockpit Layouts:
    - Pilot: Cockpit/Pilot.md
    - Gunner: Cockpit/Gunner.md
  - Radios:
    - C-1611 Intercom: Radios/Intercom.md
    - AN/ARC-51 UHF: Radios/ARC51.md
    - AN/ARC-131 FM: Radios/ARC131.md
  - Navigation:
    - AN/ARN-83 ADF: Navigation/ARN83.md
  - Weapons:
    - Overview: Weapons/Overview.md
    - Employment: Weapons/Employment.md
    - AI Gunner: Weapons/AIGunner.md
  - Misc.:
    - Accessories: Misc/Accessories.md


theme:
  # logo: "images/AH-1G_Logo.png"
  favicon: "images/AH-1G_Logo.png"
  name: material
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch-off
      name: Switch to system preference
    features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

# plugins:
  # - to-pdf
