site_name: DCS AH-1G Cobra Manual

nav:
  - Introduction: index.md

  - Simulator Basics:
      - Installation: simulator/installation.md
      - Controls Setup: simulator/controls.md
      - Special Options: simulator/special-options.md

  - Aircraft Reference:
      - History And Overview: aircraft/history-overview.md
      - Rear Cockpit: aircraft/rear-cockpit.md
      - Front Cockpit: aircraft/front-cockpit.md

  - Flight Fundamentals:
      - Helicopter Flight Theory: fundamentals/helicopter-flight-theory.md
      - Maneuvers: fundamentals/maneuvers.md

  - Procedures:
      - Startup: procedures/startup.md
      - Takeoff: procedures/takeoff.md
      - Hovering: procedures/hovering.md
      - Landing: procedures/landing.md
      - Shutdown: procedures/shutdown.md
      - Refueling And Rearming: procedures/refueling-rearming.md

  - Mission Systems:
      - Navigation: mission-systems/navigation.md
      - Radio Communications: mission-systems/radio-communications.md

  - Weapons Systems:
    - Weapons Overview: weapons/weapons-overview.md
    - Weapons Employment: weapons/weapons-employment.md
    - AI Gunner Employment: weapons/ai-gunner.md

  - Appendices:
      - Abbreviated Checklists: appendices/checklists.md
      - Glossary: appendices/glossary.md

use_directory_urls: false

theme:
  # logo: "images/AH-1G_Logo.png"
  favicon: "images/AH-1G_Logo.png"
  name: material
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch-off
      name: Switch to system preference
    features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.blocks.caption
  - toc:
      permalink: "#"

extra_css:
  - css/drafts.css
  - css/images.css
  - css/links.css
  - css/headers.css
  - css/calculators.css
  - css/sidebar.css
  - css/tags.css

extra_javascript:
  - Calculators/Scripts/hover.js
# plugins:
  # - to-pdf
